# Generated by Django 4.1.3 on 2023-04-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuarios_options_alter_usuarios_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='username',
            field=models.EmailField(default='defaultEmail@gotmail.com', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
