# Generated by Django 4.1.3 on 2023-05-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuarios_username_alter_usuarios_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='username',
            field=models.EmailField(default='defaultEmail@hotmail.com', max_length=100, unique=True),
        ),
    ]
